AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notify Slack Train Delay

Globals:
  Function:
    Timeout: 10

Resources:

  NotifyPeriodicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: periodic.lambda_handler
      Runtime: python3.6
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Events:
        NotifySlack:
          Type: Schedule
          Properties:
            # 毎日 日本時間AM7時1分から10分毎（AM10時まで18回）
            # 毎日 日本時間PM5時1分から10分毎（PM8時まで18回）
            Schedule: cron(1/10 22-0,8-10 * * ? *)

  NotifySlashCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: slash_command.lambda_handler
      Runtime: python3.6
      Events:
        SlashCommand:
          Type: Api
          Properties:
            Path: /train/notification
            Method: POST


Outputs:

  SlashCommandApi:
    Description: "Slash command API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/train/notification"
